secrets:
  htpasswd: |-
    <registry_username>:<registry_basic_auth_token>
ingress:
  enabled: true
  hosts:
    - <registry_hostname>
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: “true”
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls:
    - secretName: tls-prod-cert
      hosts:
      - <registry_hostname>
persistence:
  enabled: true
  existingClaim: registry
