apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-manager
spec:
  selector:
    matchLabels:
      name: app-manager
  replicas: 1
  template:
    metadata:
      labels:
        name: app-manager
    spec:
      containers:
        - name: app-manager
          image: "docker.io/columbustech/app-manager:dev"
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-manager
