apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cdrive
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: “true”
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
  - host: api.cdrive.columbusecosystem.com
    http:
      paths: 
      - path: /
        backend:
          serviceName: cdrive 
          servicePort: 8000
  tls:
  - secretName: tls-staging-cert
    hosts:
    - api.cdrive.columbusecosystem.com

