apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: authentication
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: “true”
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: authentication.columbusecosystem.com
    http:
      paths: 
      - path: /
        backend:
          serviceName: authentication
          servicePort: 8000
  tls:
  - secretName: tls-prod-cert
    hosts:
    - authentication.columbusecosystem.com
    - cdrive.columbusecosystem.com
    - api.cdrive.columbusecosystem.com
